fix: duplicate revision decryption
standardnotes/snjs pull request #123
Opened 2020-10-02 14:16 UTC by mobitar

- Fixes issue where revisions of an item that is created from a duplication event couldn't be decrypted

2020-10-02 14:18 UTC, mobitar commented on lib/index.ts
> +  uniqCombineObjArrays,
Just sorted this alphabetically..

2020-10-02 14:21 UTC, mobitar commented on lib/protocol/operator/004/operator_004.ts
> +          omitUndefinedCopy(
Technically JSON.stringify will already omit any keys for which the value is undefined. But I didn't want to count on this being an implementation detail of web browsers. Perhaps React Native does it differently. So this is why we omit undefined keys explicitly.

2020-10-04 03:20 UTC, johnny243 requested changes
Tests for remote history seems to be failing

2020-10-04 14:08 UTC, mobitar commented
@johnny243 you'd need to run tests in using development environment so that jobs can run, in order for revision tests to succeed.

2020-10-05 13:06 UTC, merged